-------------------------------------------------------------------------
--게시판생성
-------------------------------------------------------------------------
CREATE TABLE BOARD (	
    "BOARDNO" NUMBER, 
	"BOARDTITLE" VARCHAR2(50), 
	"BOARDWRITER" VARCHAR2(15),
    "BOARDCONTENT" VARCHAR2(2000), 
	"BOARDDATE" DATE DEFAULT SYSDATE, 
	"BOARDREADCOUNT" NUMBER DEFAULT 0, 
    CONSTRAINT PK_BOARDNO PRIMARY KEY(BOARDNO),
    CONSTRAINT FK_BOARDWRITER FOREIGN KEY(BOARDWRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL
);

COMMENT ON COLUMN "BOARD"."BOARDNO" IS '게시글번호';
COMMENT ON COLUMN "BOARD"."BOARDTITLE" IS '게시글제목';
COMMENT ON COLUMN "BOARD"."BOARDWRITER" IS '게시글작성자 아이디';
COMMENT ON COLUMN "BOARD"."BOARDCONTENT" IS '게시글내용';
COMMENT ON COLUMN "BOARD"."BOARDDATE" IS '게시글올린날짜';
COMMENT ON COLUMN "BOARD"."BOARDREADCOUNT" IS '조회수';

--게시판시퀀스생성
CREATE SEQUENCE SEQ_BOARDNO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


-------------------------------------------------------------------------
--첨부파일 생성
-------------------------------------------------------------------------
CREATE TABLE ATTACHMENT (
  ATTACHMENTNO NUMBER PRIMARY KEY,
  BOARDNO NUMBER NOT NULL,
  ORIGINALFILENAME VARCHAR2(255) NOT NULL,
  RENAMEDFILENAME VARCHAR2(255) NOT NULL,
  UPLOADDATE DATE DEFAULT SYSDATE,
  DOWNLOADCOUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  CONSTRAINT FK_BOARDNO FOREIGN KEY(BOARDNO) REFERENCES BOARD(BOARDNO) ON DELETE CASCADE
);

COMMENT ON COLUMN ATTACHMENT.ATTACHMENTNO IS '첨부파일번호(PK)';
COMMENT ON COLUMN ATTACHMENT.BOARDNO IS '게시판글번호(FK)';
COMMENT ON COLUMN ATTACHMENT.ORIGINALFILENAME IS '업로드한 첨부파일명';
COMMENT ON COLUMN ATTACHMENT.RENAMEDFILENAME IS '서버에 저장된 첨부파일명';
COMMENT ON COLUMN ATTACHMENT.UPLOADDATE IS '업로드일자';
COMMENT ON COLUMN ATTACHMENT.DOWNLOADCOUNT IS '다운로드 횟수';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '사용여부';



CREATE SEQUENCE SEQ_ATTACHMENTNO
START WITH 2
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

	


Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 1','user01','반갑습니다',to_date(SYSDATE-60,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 2','user02','안녕하세요',to_date(SYSDATE-59,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 3','admin','반갑습니다',to_date(SYSDATE-58,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 4','user01','안녕하세요',to_date(SYSDATE-57,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 5','user02','반갑습니다',to_date(SYSDATE-56,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 6','admin','안녕하세요',to_date(SYSDATE-55,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 7','user01','반갑습니다',to_date(SYSDATE-54,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 8','user02','안녕하세요',to_date(SYSDATE-53,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 9','admin','반갑습니다',to_date(SYSDATE-52,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 10','user01','안녕하세',to_date(SYSDATE-51,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 11','user02','반갑습니다',to_date(SYSDATE-50,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 12','admin','안녕하세',to_date(SYSDATE-49,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 13','user01','반갑습니다',to_date(SYSDATE-48,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 14','user02','안녕하세',to_date(SYSDATE-47,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 15','admin','반갑습니다',to_date(SYSDATE-46,'RR/MM/DD'),0);


Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 16','user01','안녕하세',to_date(SYSDATE-45,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 17','user02','반갑습니다',to_date(SYSDATE-44,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 18','admin','안녕하세',to_date(SYSDATE-43,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 19','user01','반갑습니다',to_date(SYSDATE-42,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 20','user02','안녕하세',to_date(SYSDATE-41,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 21','admin','반갑습니다',to_date(SYSDATE-40,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 22','user01','안녕하세',to_date(SYSDATE-39,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 23','user02','반갑습니다',to_date(SYSDATE-38,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 24','admin','안녕하세',to_date(SYSDATE-37,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 25','user01','반갑습니다',to_date(SYSDATE-36,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 26','user02','안녕하세',to_date(SYSDATE-35,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 27','admin','반갑습니다',to_date(SYSDATE-34,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 28','user01','안녕하세',to_date(SYSDATE-33,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 29','user02','반갑습니다',to_date(SYSDATE-32,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 30','admin','안녕하세',to_date(SYSDATE-31,'RR/MM/DD'),0);

Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 31','user01','반갑습니다',to_date(SYSDATE-30,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 32','user02','안녕하세',to_date(SYSDATE-29,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 33','admin','반갑습니다',to_date(SYSDATE-28,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 34','user01','안녕하세',to_date(SYSDATE-27,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 35','user02','반갑습니다',to_date(SYSDATE-26,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 36','admin','안녕하세',to_date(SYSDATE-25,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 37','user01','반갑습니다',to_date(SYSDATE-24,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 38','user02','안녕하세',to_date(SYSDATE-23,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 39','admin','반갑습니다',to_date(SYSDATE-22,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 40','user01','안녕하세',to_date(SYSDATE-21,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 41','user02','반갑습니다',to_date(SYSDATE-20,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 42','admin','안녕하세',to_date(SYSDATE-19,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 43','user01','반갑습니다',to_date(SYSDATE-18,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 44','user02','안녕하세',to_date(SYSDATE-17,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 45','admin','반갑습니다',to_date(SYSDATE-16,'RR/MM/DD'),0);

Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 46','user01','안녕하세',to_date(SYSDATE-15,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 47','user02','반갑습니다',to_date(SYSDATE-14,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 48','admin','안녕하세',to_date(SYSDATE-13,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 49','user01','반갑습니다',to_date(SYSDATE-12,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 50','user02','안녕하세',to_date(SYSDATE-11,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 51','admin','반갑습니다',to_date(SYSDATE-10,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 52','user01','안녕하세',to_date(SYSDATE-9,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 53','user02','반갑습니다',to_date(SYSDATE-8,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 54','admin','안녕하세',to_date(SYSDATE-7,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 55','user01','반갑습니다',to_date(SYSDATE-6,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 56','user02','안녕하세',to_date(SYSDATE-5,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 57','admin','반갑습니다',to_date(SYSDATE-4,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 58','user01','안녕하세',to_date(SYSDATE-3,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 59','user02','반갑습니다',to_date(SYSDATE-2,'RR/MM/DD'),0);
Insert into BOARD (BOARDNO,BOARDTITLE,BOARDWRITER,BOARDCONTENT,BOARDDATE,BOARDREADCOUNT) values (SEQ_BOARDNO.nextval,'안녕하세요, 게시판입니다 - 60','admin','안녕하세',to_date(SYSDATE-1,'RR/MM/DD'),0);

select * from board;
select * from member;

COMMIT;